models/Clients.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "clients".
 *
 * @property int $id
 * @property string $email
 * @property string $fullname
 * @property string $firstname
 * @property string $lastname
 * @property string $phone
 * @property string $mobile
 * @property string $phone2
 * @property string $mobile2
 * @property string $address
 * @property string $address_floor
 * @property string $address_area
 * @property string $town
 * @property string $postal_code
 * @property string $created_at
 * @property string $updated_at
 * @property int $open_order
 */
class Clients extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'clients';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['fullname', 'open_order'], 'required'],
            [['open_order'], 'integer'],
            [['created_at', 'updated_at'], 'string'],
            [['email', 'fullname', 'firstname', 'lastname', 'address', 'town'], 'string', 'max' => 255],
            [['phone', 'mobile', 'phone2', 'mobile2', 'address_floor', 'address_area', 'postal_code'], 'string', 'max' => 55],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'email' => 'Email',
            'fullname' => 'Ονοματεπώνυμο',
            'firstname' => 'Όνομα',
            'lastname' => 'Επώνυμο',
            'phone' => 'Τηλέφωνο',
            'mobile' => 'Κινητό',
            'phone2' => 'Τηλέφωνο 2',
            'mobile2' => 'Κινητό 2',
            'address' => 'Διεύθυνση',
            'address_floor' => 'Όροφος',
            'address_area' => 'Περιοχή',
            'town' => 'Πόλη',
            'postal_code' => 'ΤΚ',
            'created_at' => 'Δημιουργήθηκε στις',
            'updated_at' => 'Ενημερώθηκε στις',
            'open_order' => 'Κατάσταση παραγγελίας',
        ];
    }

    public function getFullname($client_id) {
        $data = (new \yii\db\Query())->select(['fullname'])->from('clients')->where(['id' => $client_id]);
        $command = $data->createCommand();
        $results = $command->queryAll();
        return $results;
    }

//    public function getUser($uid) {
//        $data = Clients::find()->select(['id','fullname'])->where(['id'=> $uid]);
//        return $data;
//    }

    public function getAllUsers() {
        $data = Contractor::find()->select(['id','fullname','mobile','phone','email'])->all();
        return $data;
    }
}

controllers/ClientOrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Payments;
use app\models\Clients;
use app\models\Contractor;
use app\models\ClientOrder;
use app\models\ClientOrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientOrderController implements the CRUD actions for ClientOrder model.
 */
class ClientOrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['create', 'update','index'],
                'rules' => [
                    // deny all POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST']
                    ],
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all ClientOrder models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientOrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataUsers = new Clients();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'getUsers' => $dataUsers,
        ]);
    }

    /**
     * Displays a single ClientOrder model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
    	
    	$findContractor = new Contractor();
        $order_payment_info = new Payments();
        $order_id = $_GET['id'];

        //ds - get client information
        $attrs = new ClientOrder();
        $client_id = $attrs->getClientID($order_id); //return array
            //var_dump($client_id);
            //echo $client_id[0]['client_id'];

        $client_fulname = $attrs->getClientInfo($client_id[0]['client_id']); //return array
//        echo $client_fulname[0]['fullname'];
//        var_dump($client_fulname);


        return $this->render('view', [
            'model'                     => $this->findModel($id),
            'attrs'                     => $attrs->attributeLabels(),
	        'contractor_names'          => $findContractor->getAllContractor(),
	        'payment_order_information' => $order_payment_info->getPaymentsById($order_id),
            'client_info_fullname'      => $client_fulname[0]['fullname'],
        ]);
    }

    /**
     * Creates a new ClientOrder model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClientOrder();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        //echo $_GET['id'];
        if(isset($_GET['id']) && !empty($_GET['id'])) {
            $model->client_id = $_GET['id'];
        }

        $last_order_number = new ClientOrder();
        $order_number_last = $last_order_number->getLastOrderNumber();
        //        var_dump($order_number_last[0]);
        $current_last_order_number = $order_number_last[0]['order_number'];
        $current_last_order_number += 1;
        $model->order_number = $current_last_order_number;
	
	    //ds - get the names of contractors
	    $contractor = new Contractor();
	    $model->contractor_id = $contractor->getAllContractor();
		//var_dump($model);

        //set default values
        $model->created_at = date('Y-m-d');
        $model->updated_at = date('Y-m-d');
        $model->order_date = date('Y-m-d');

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    /**
     * Updates an existing ClientOrder model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
	
	    //ds - get the names of contractors
	    $contractor = new Contractor();
	    $model->contractor_id = $contractor->getAllContractor();

        //ds - get client information
        $attrs = new ClientOrder();
        $client_id = $attrs->getClientID($id); //return array
        $client_fulname = $attrs->getClientInfo($client_id[0]['client_id']); //return array

        $model->updated_at = date('Y-m-d');

        return $this->render('update', [
            'model' => $model,
            'client_info_fullname' => $client_fulname[0]['fullname'],
        ]);
    }

    /**
     * Deletes an existing ClientOrder model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ClientOrder model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClientOrder the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClientOrder::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ClientsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clients;
use app\models\ClientsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientsController implements the CRUD actions for Clients model.
 */
class ClientsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['create', 'update','index'],
                'rules' => [
                    // deny all POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST']
                    ],
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all Clients models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clients model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clients model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clients();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clients model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clients model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function getFullname() { //paymentsController

    }

    /**
     * Finds the Clients model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clients the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clients::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/clients/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clients-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'fullname')->textInput(['maxlength' => true]) ?>

<!--    --><?//= $form->field($model, 'firstname')->textInput(['maxlength' => true]) ?>
<!---->
<!--    --><?//= $form->field($model, 'lastname')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'mobile2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone2')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address_floor')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'address_area')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'town')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'postal_code')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'created_at')->input('date') ?>
<!--    $form->field($model, 'created_at')->textInput(['maxlength' => true]) -->

    <?= $form->field($model, 'updated_at')->input('date') ?>
<!--  $form->field($model, 'updated_at')->textInput(['maxlength' => true]) -->
	
	<?php
	echo $form->field($model, 'open_order')->dropDownList(['0' => 'Ανοιχτή', '1' => 'Κλειστή', '2' => 'Άκυρη']);
	?>

    <div class="form-group">
        <?= Html::submitButton('Αποθήκευση', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clients/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ClientsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="clients-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'email') ?>

<<<<<<< HEAD
    <?= $form->field($model, 'fullname') ?>

=======
>>>>>>> 7381280fdc260203c1e811470dabe1ec6ba3f032
    <?= $form->field($model, 'firstname') ?>

    <?= $form->field($model, 'lastname') ?>

<<<<<<< HEAD
    <?php // echo $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'mobile') ?>

    <?php // echo $form->field($model, 'phone2') ?>

    <?php // echo $form->field($model, 'mobile2') ?>

    <?php // echo $form->field($model, 'address') ?>

    <?php // echo $form->field($model, 'address_floor') ?>

    <?php // echo $form->field($model, 'address_area') ?>

=======
    <?= $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'mobile') ?>

    <?php // echo $form->field($model, 'address') ?>

>>>>>>> 7381280fdc260203c1e811470dabe1ec6ba3f032
    <?php // echo $form->field($model, 'town') ?>

    <?php // echo $form->field($model, 'postal_code') ?>

<<<<<<< HEAD
    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

=======
>>>>>>> 7381280fdc260203c1e811470dabe1ec6ba3f032
    <?php // echo $form->field($model, 'open_order') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/clients/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = 'Δημιουργία νέου πελάτη';
$this->params['breadcrumbs'][] = ['label' => 'Πελάτες', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clients-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clients/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ClientsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Πελάτες';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="clients-index">
    <h1><?= Html::encode($this->title) ?></h1>
    <p><?= Html::a('Νέος Πελάτης', ['create'], ['class' => 'btn btn-success']) ?></p>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'], //add A/A in first column
            'fullname',
            //'firstname',
            //'lastname',
            'phone',
            'mobile',
            //'phone2',
            //'mobile2',
            'address',
            //'address_floor',
            //'address_area',
            //'town',
            //'postal_code',
            //'created_at',
            //'updated_at',
//            'email:email',
//            'open_order',
            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
</div>

views/clients/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = 'Ενημέρωση πελάτη: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Πελάτες', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Ενημέρωση';
?>
<div class="clients-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/clients/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Clients */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Πελάτες', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="clients-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php
//        var_dump($_GET);
//        echo $_GET['id'];
        ?>
        <?= Html::a('Νέα παραγγελία', ['client-order/create', 'id' => $_GET['id']], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Ενημέρωση πελάτη', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Διαγραφή πελάτη', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Είστε σίγουροι ότι θέλετε να διαγράψετε αυτόν τον πελάτη;',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'email:email',
            'fullname',
//            'firstname',
//            'lastname',
            'phone',
            'mobile',
            'phone2',
            'mobile2',
            'address',
            'address_floor',
            'address_area',
            'town',
            'postal_code',
            'created_at',
            'updated_at',
//            array(
//                'open_order',
//                'value' => (($model->open_order == 0) ? "Κλειστή": "Ανοιχτή"),
//                'attribute'=>'Κατάσταση παραγγελίας',
//            ),
        ],
    ]) ?>

</div>