models/Payments.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "client_order_payment".
 *
 * @property int $id
 * @property int $order_id
 * @property string $trans_date
 * @property string $reason
 * @property float $amount
 * @property string $apodeiksi
 * @property string $created_at
 * @property string $updated_at
 */
class Payments extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'client_order_payment';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['order_id'], 'integer'],
            [['trans_date', 'created_at', 'updated_at'], 'safe'],
//            [['trans_date', 'created_at', 'updated_at'], 'date'],
            [['amount'], 'number'],
            [['reason'], 'string', 'max' => 255],
            [['apodeiksi'], 'string', 'max' => 20],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'order_id' => 'ID παραγγελίας',
            'trans_date' => 'Ημ/νία συναλλαγής',
            'reason' => 'Αιτιολογία',
            'amount' => 'Ποσό* (Καθαρό ποσό χωρίς σύμβολα € πχ. 1000)',
            'apodeiksi' => 'Αρ. Απόδειξης', //deleted - user does not want them
            'created_at' => 'Ημέρα πληρωμής',
            'updated_at' => 'Τελευταία ενημέρωση',
        ];
    }
    public function getPaymentsById($order_id) {
        $data = (new \yii\db\Query())->select(['id','order_id','trans_date','reason','amount','apodeiksi','created_at','updated_at'])->from('client_order_payment')->where(['order_id' => $order_id]);
        $command = $data->createCommand();
        $results = $command->queryAll();
        return $results;
    }

    public function getClientID($order_id) { //paymentsController
        $data = (new \yii\db\Query())->select(['client_id'])->from('client_order')->where(['id' => $order_id]);
        $command = $data->createCommand();
        $results = $command->queryAll();
        return $results;
    }

    public function getClientInfo($client_id)
    {
        $data = (new \yii\db\Query())->select(['fullname','email','phone','phone2','mobile','mobile2'])->from('clients')->where(['id' => $client_id]);
        $command = $data->createCommand();
        $results = $command->queryAll();
        return $results;
    }
}

controllers/ClientOrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Payments;
use app\models\Clients;
use app\models\Contractor;
use app\models\ClientOrder;
use app\models\ClientOrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientOrderController implements the CRUD actions for ClientOrder model.
 */
class ClientOrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['create', 'update','index'],
                'rules' => [
                    // deny all POST requests
                    [
                        'allow' => true,
                        'verbs' => ['POST']
                    ],
                    // allow authenticated users
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    // everything else is denied
                ],
            ],
        ];
    }

    /**
     * Lists all ClientOrder models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientOrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataUsers = new Clients();

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'getUsers' => $dataUsers,
        ]);
    }

    /**
     * Displays a single ClientOrder model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
    	
    	$findContractor = new Contractor();
        $order_payment_info = new Payments();
        $order_id = $_GET['id'];

        //ds - get client information
        $attrs = new ClientOrder();
        $client_id = $attrs->getClientID($order_id); //return array
            //var_dump($client_id);
            //echo $client_id[0]['client_id'];

        $client_fulname = $attrs->getClientInfo($client_id[0]['client_id']); //return array
//        echo $client_fulname[0]['fullname'];
//        var_dump($client_fulname);


        return $this->render('view', [
            'model'                     => $this->findModel($id),
            'attrs'                     => $attrs->attributeLabels(),
	        'contractor_names'          => $findContractor->getAllContractor(),
	        'payment_order_information' => $order_payment_info->getPaymentsById($order_id),
            'client_info_fullname'      => $client_fulname[0]['fullname'],
        ]);
    }

    /**
     * Creates a new ClientOrder model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClientOrder();


        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        //echo $_GET['id'];
        if(isset($_GET['id']) && !empty($_GET['id'])) {
            $model->client_id = $_GET['id'];
        }

        $last_order_number = new ClientOrder();
        $order_number_last = $last_order_number->getLastOrderNumber();
        //        var_dump($order_number_last[0]);
        $current_last_order_number = $order_number_last[0]['order_number'];
        $current_last_order_number += 1;
        $model->order_number = $current_last_order_number;
	
	    //ds - get the names of contractors
	    $contractor = new Contractor();
	    $model->contractor_id = $contractor->getAllContractor();
		//var_dump($model);

        //set default values
        $model->created_at = date('Y-m-d');
        $model->updated_at = date('Y-m-d');
        $model->order_date = date('Y-m-d');

        return $this->render('create', [
            'model' => $model,
        ]);
    }
    
    /**
     * Updates an existing ClientOrder model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
	
	    //ds - get the names of contractors
	    $contractor = new Contractor();
	    $model->contractor_id = $contractor->getAllContractor();

        //ds - get client information
        $attrs = new ClientOrder();
        $client_id = $attrs->getClientID($id); //return array
        $client_fulname = $attrs->getClientInfo($client_id[0]['client_id']); //return array

        $model->updated_at = date('Y-m-d');

        return $this->render('update', [
            'model' => $model,
            'client_info_fullname' => $client_fulname[0]['fullname'],
        ]);
    }

    /**
     * Deletes an existing ClientOrder model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ClientOrder model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClientOrder the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClientOrder::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/PaymentsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Payments;
use app\models\PaymentsSeach;
use app\models\Clients;
use app\models\ClientOrder;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * PaymentsController implements the CRUD actions for Payments model.
 */
class PaymentsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Payments models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PaymentsSeach();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Payments model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Payments model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Payments();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }
        
        if(isset($_GET['order_id']) && !empty($_GET['order_id'])) {
        	$model->order_id = $_GET['order_id'];
        }

        $order_id = $_GET['order_id']; //1331

        //get client_id from client_order tbl
        $clientOrder = new ClientOrder();
        $db_client_id = $clientOrder->getClientID($order_id); //returns array
        $client_id = $db_client_id[0]["client_id"];
        //var_dump($db_client_id);

        $clients = new Clients();
        $client_info = $clients->getFullname($client_id);
        $client_info_fullname = $client_info[0]["fullname"];
			//$model->fullname = $client_info_fullname;
            //var_dump($client_info);
	
	    //default values to Dates input fields
	        //$model->created_at = date('d/m/Y');
	    $model->trans_date = date('Y-m-d');
	        //$model->updated_at = date('d/m/Y');

        return $this->render('create', [
            'model'                 => $model,
            'client_info_fullname'  => $client_info_fullname,
        ]);
    }

    /**
     * Updates an existing Payments model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Payments model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Payments model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Payments the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Payments::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/payments/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="payments-form">

    <?php $form = ActiveForm::begin(); ?>
	
	<div class="container">
        <div class="row">
            <div class="col-md-12">
                <?php
                echo '<h3><strong>Ονοματεπώνυμο πελάτη:</strong> '. $fullname . '</h3>';
                ?>
            </div>
        </div>

		<div class="row">
			<div class="col-md-12">
				<?= $form->field($model, 'order_id')->textInput() ?>
			</div>
		</div>

<!--        <div class="row">-->
<!--			<div class="col-md-12">-->
<!--                --><?php //echo $fullname; ?>
<!--			</div>-->
<!--		</div>-->
		
		<div class="row">
			<div class="col-md-12">
				<?=  $form->field($model, 'trans_date')->input('date') ?>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<?= $form->field($model, 'reason')->textInput(['maxlength' => true]) ?>
			</div>
		</div>
		
		<div class="row">
			<div class="col-md-12">
				<?= $form->field($model, 'amount')->textInput() ?>
			</div>
		</div>
		
<!--		<div class="row">-->
<!--			<div class="col-md-12">-->
<!--				--><?//= $form->field($model, 'apodeiksi')->textInput(['maxlength' => true]) ?>
<!--			</div>-->
<!--		</div>-->
		
		<!--<div class="row">-->
		<!--	<div class="col-md-12">-->
		<!--		--><?//= $form->field($model, 'created_at')->input('date') ?>
		<!--	</div>-->
		<!--</div>-->
		<!---->
		<!--<div class="row">-->
		<!--	<div class="col-md-12">-->
		<!--		--><?//= $form->field($model, 'updated_at')->input('date') ?>
		<!--	</div>-->
		<!--</div>-->
		
	</div>
	
    <div class="form-group">
        <?= Html::submitButton('Αποθήκευση', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/payments/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PaymentsSeach */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="payments-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'order_id') ?>

    <?= $form->field($model, 'trans_date') ?>

    <?= $form->field($model, 'reason') ?>

    <?= $form->field($model, 'amount') ?>

    <?php // echo $form->field($model, 'apodeiksi') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/payments/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Δημιουργία πληρωμής';
$this->params['breadcrumbs'][] = ['label' => 'Πληρωμές', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model'     => $model,
	    'fullname'  => $client_info_fullname,
    ]) ?>

</div>

views/payments/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PaymentsSeach */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Πληρωμές';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="payments-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Δημιουργία ππληρωμής', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'], //add A/A in first column
            //'id',
            'order_id',
            'trans_date',
            'reason',
            [
                'attribute' => 'amount',
                'value' => function($model) {return number_format($model->amount,2,',','.'); },
            ],
            //'apodeiksi',
            //'created_at',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

views/payments/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = 'Ενημέρωση πληρωμής: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Payments', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Ενημέρωση';
?>
<div class="payments-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/payments/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Payments */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Πληρωμές', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="payments-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Ενημέρωση', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Διαγραφή', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Είστε σίγουρος ότι θέλετε να διαγράψετε αυτή την πληρωμή;',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('Επιστροφή στον πελάτη', ['client-order/view', 'id' => $model->order_id], ['class' => 'btn btn-success']) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'order_id',
            'trans_date',
            'reason',
            [
                'attribute' => 'amount',
                'value' => number_format($model->amount,2,',','.'),
            ],
//            'amount',
            'apodeiksi',
            //'created_at',
            //'updated_at',
        ],
    ]) ?>

</div>